### PR TITLE
feat: Custom storage key names

### PR DESCRIPTION
**Pull request by huntabyte**
Closes: #75 

You can now pass `themeStorageKey` and `modeStorageKey` props to `<ModeWatcher>` to customize the key used in local storage for the theme and mode.

### CODE REVIEW

**Comment by shyakadavis** [comment]
Hey, Hunter 👋 

Curious, why aren't you using `pnpm/action-setup@v4`? Cause v4 saves you the trouble of not having to configure all that stuff of setting up cache and what-have-you.

**Comment by huntabyte** [comment]
> Hey, Hunter 👋
> 
> Curious, why aren't you using `pnpm/action-setup@v4`? Cause v4 saves you the trouble of not having to configure all that stuff of setting up cache and what-have-you.

I didn't know this was the case tbh!

**Comment by shyakadavis** [comment]
Oh, okay. Here is a reference if you'd like:

- https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time

**Comment by shyakadavis** [comment]
Some time back, all my CI's started failing with no warning, and turns out the mandate was to upgrade. 😅

**Comment by huntabyte** [comment]
> Some time back, all my CI's started failing with no warning, and turns out the mandate was to upgrade. 😅

Thank you! Just updated all the pipelines! Appreciate it!

**Pull request merged**
