### PR TITLE
fix: hydration issues

### PR DESCRIPTION
**Pull request by jdgamble555**
Get rid of mode-watcher warning for Svelte 5 users.

### CODE REVIEW

**Review by huntabyte — APPROVED** [review]
Thank you!

**Comment by dhust** [comment]
Not sure if the Merged means it's finished, but it's still showing the hydration message:

`[svelte] hydration_html_changedThe value of an `{@html ...}` block in node_modules/​mode-watcher/​dist/​mode-watcher-full.svelte changed between server and client renders. The client value will be ignored in favour of the server value`

I'm using `mode-watcher@0.5.0`
I tried putting `svelte-ignore` in multiple places but I couldn't get it to work.

**Comment by jdgamble555** [comment]
My merge didn't fix the problem. It was really a hack in Svelte 4. I believe he is going to rewrite it to use cookies, which I believe is the only real way to load from the server.

Now, when? No idea...

J

**Comment by ollema** [comment]
> My merge didn't fix the problem. It was really a hack in Svelte 4. I believe he is going to rewrite it to use cookies, which I believe is the only real way to load from the server.
> 
> Now, when? No idea...
> 
> J

using cookies is not always an option so that can’t be the only mode in which mode-watcher operates.

see https://github.com/sveltejs/svelte/pull/14397#issuecomment-2555814603 and the response two comments below from Rich.

so mode-watcher might add an option to use it with cookies but there will always exist a need for a localStorage based solution that inserts code into <head>

**Comment by jdgamble555** [comment]
As far as I know, there is no way to load data from local storage before the html has been rendered in Svelte 5, hence the problem at hand.

J

**Comment by ollema** [comment]
> As far as I know, there is no way to load data from local storage before the html has been rendered in Svelte 5, hence the problem at hand.
> 
> J

what we are doing now with mode-watcher works in practice also for svelte 5 right?

as in the snippet inspired into the head successfully sets the correct html element class preventing flash of unstyled content.

there is a slight annoyance that there is a hydration mismatch. but that warning does not affect the functionality and it still works as intended no?

**Comment by huntabyte** [comment]
> there is a slight annoyance that there is a hydration mismatch. but that warning does not affect the functionality and it still works as intended no?

Correct.

The only possible way to prevent a hydration mismatch is to get the data on the server, which as you mentioned isn't always feasible, so users of Svelte 5 _without_ SvelteKit will continue to get this warning.

It really should be possible to filter out because it's super annoying, especially considering it doesn't actually impact anything and there _should_ be a mismatch between server and client since we are retrieving the values on the client 🤦‍♂️

**Comment by jdgamble555** [comment]
The docs say that it is possible to disable the warning (must be new), I just can't get it to work. This is specifically a runtime error, not a compile error, but we should be able to ignore either.

https://svelte.dev/docs/svelte/runtime-warnings#Client-warnings-hydration_html_changed

So, I would think this?

```html
<!-- svelte-ignore hydration_html_changed -->
```

I tried this, to no avail:
```html
<svelte:head>
	{#if themeColors}
		<!-- default to dark mode for to allow testing -->
		<!-- this will be overwritten by FOUC prevention snippet below -->
		<!-- but that snippet does not run in vitest -->
		<meta name="theme-color" content={themeColors.dark} />
	{/if}
	<!-- eslint-disable-next-line svelte/no-at-html-tags, prefer-template -->
	<!-- svelte-ignore hydration_html_changed -->
	{@html `<script${trueNonce ? ` nonce=${trueNonce}` : ''}>(` +
		setInitialMode.toString() +
		`)(` +
		JSON.stringify(initConfig) +
		`);</script>`}
</svelte:head>
```

If anyone else has any ideas...

J

**Comment by jdgamble555** [comment]
@huntabyte - It looks like the `svelte-ignore` does work!

I created a test repository:

https://github.com/jdgamble555/svelte-hydration-error/blob/master/src/routes/%2Blayout.svelte

Should we update this for now?

J

**Comment by jdgamble555** [comment]
@dhust - I think it needs to be put in the `mode-watcher` package on [this line](https://github.com/svecosystem/mode-watcher/blob/5021963a3841de36cda7dfc28919a9a9afa4469e/packages/mode-watcher/src/lib/mode-watcher-full.svelte#L17).  Calling `<ModeWatcher />` isn't the problem, it is the node module package itself I would think.

J

**Comment by dhust** [comment]
@jdgamble555 
Didn't work for me.

**Comment by jdgamble555** [comment]
@dhust - Did you put it in the `node-modules` folder on the line above, restart VS Code and your localhost? 

Try my test REPO and let me know if that works for you:

https://github.com/jdgamble555/svelte-hydration-error

J

**Comment by dhust** [comment]
@jdgamble555 - Just had to restart VSCode. Nicely done! Thank you so much.

**Comment by jdgamble555** [comment]
@huntabyte - I made a PR if you could review it please sir:

https://github.com/svecosystem/mode-watcher/pull/108

J

**Pull request merged**
